[versions]
agp = "8.5.0"
kotlin = "1.9.24"
ksp = "1.9.24-1.0.20"
compose-bom = "2024.06.00"
activity-compose = "1.9.2"
nav-compose = "2.7.7"
lifecycle = "2.8.4"
coroutines = "1.8.1"
room = "2.6.1"
material = "1.12.0"

[libraries]
